from django.utils.translation import gettext_lazy as _

COUNTRIES = (
    (0, ''),
    (1, _('Andorra')),
    (2, _('United Arab Emirates')),
    (3, _('Afghanistan')),
    (4, _('Antigua and Barbuda')),
    (5, _('Anguilla')),
    (6, _('Albania')),
    (7, _('Armenia')),
    (8, _('Netherlands Antilles')),
    (9, _('Angola')),
    (10, _('Antarctica')),
    (11, _('Argentina')),
    (12, _('American Samoa')),
    (13, _('Austria')),
    (14, _('Australia')),
    (15, _('Aruba')),
    (16, _('Azerbaijan')),
    (17, _('Bosnia and Herzegovina')),
    (18, _('Barbados')),
    (19, _('Bangladesh')),
    (20, _('Belgium')),
    (21, _('Burkina Faso')),
    (22, _('Bulgaria')),
    (23, _('Bahrain')),
    (24, _('Burundi')),
    (25, _('Benin')),
    (26, _('Bermuda')),
    (27, _('Brunei')),
    (28, _('Bolivia')),
    (29, _('Brazil')),
    (30, _('Bahamas')),
    (31, _('Bhutan')),
    (32, _('Bouvet Island')),
    (33, _('Botswana')),
    (34, _('Belarus')),
    (35, _('Belize')),
    (36, _('Canada')),
    (37, _('Cocos [Keeling] Islands')),
    (38, _('Congo [DRC]')),
    (39, _('Central African Republic')),
    (40, _('Congo [Republic]')),
    (41, _('Switzerland')),
    (42, _('Côte d`Ivoire')),
    (43, _('Cook Islands')),
    (44, _('Chile')),
    (45, _('Cameroon')),
    (46, _('China')),
    (47, _('Colombia')),
    (48, _('Costa Rica')),
    (49, _('Cuba')),
    (50, _('Cape Verde')),
    (51, _('Christmas Island')),
    (52, _('Cyprus')),
    (53, _('Czech Republic')),
    (54, _('Germany')),
    (55, _('Djibouti')),
    (56, _('Denmark')),
    (57, _('Dominica')),
    (58, _('Dominican Republic')),
    (59, _('Algeria')),
    (60, _('Ecuador')),
    (61, _('Estonia')),
    (62, _('Egypt')),
    (63, _('Western Sahara')),
    (64, _('Eritrea')),
    (65, _('Spain')),
    (66, _('Ethiopia')),
    (67, _('Finland')),
    (68, _('Fiji')),
    (69, _('Falkland Islands [Islas Malvinas]')),
    (70, _('Micronesia')),
    (71, _('Faroe Islands')),
    (72, _('France')),
    (73, _('Gabon')),
    (74, _('United Kingdom')),
    (75, _('Grenada')),
    (76, _('Georgia')),
    (77, _('French Guiana')),
    (78, _('Guernsey')),
    (79, _('Ghana')),
    (80, _('Gibraltar')),
    (81, _('Greenland')),
    (82, _('Gambia')),
    (83, _('Guinea')),
    (84, _('Guadeloupe')),
    (85, _('Equatorial Guinea')),
    (86, _('Greece')),
    (87, _('South Georgia and the South Sandwich Islands')),
    (88, _('Guatemala')),
    (89, _('Guam')),
    (90, _('Guinea-Bissau')),
    (91, _('Guyana')),
    (92, _('Gaza Strip')),
    (93, _('Hong Kong')),
    (94, _('Heard Island and McDonald Islands')),
    (95, _('Honduras')),
    (96, _('Croatia')),
    (97, _('Haiti')),
    (98, _('Hungary')),
    (99, _('Indonesia')),
    (100, _('Ireland')),
    (101, _('Israel')),
    (102, _('Isle of Man')),
    (103, _('India')),
    (104, _('British Indian Ocean Territory')),
    (105, _('Iraq')),
    (106, _('Iran')),
    (107, _('Iceland')),
    (108, _('Italy')),
    (109, _('Jersey')),
    (110, _('Jamaica')),
    (111, _('Jordan')),
    (112, _('Japan')),
    (113, _('Kenya')),
    (114, _('Kyrgyzstan')),
    (115, _('Cambodia')),
    (116, _('Kiribati')),
    (117, _('Comoros')),
    (118, _('Saint Kitts and Nevis')),
    (119, _('North Korea')),
    (120, _('South Korea')),
    (121, _('Kuwait')),
    (122, _('Cayman Islands')),
    (123, _('Kazakhstan')),
    (124, _('Laos')),
    (125, _('Lebanon')),
    (126, _('Saint Lucia')),
    (127, _('Liechtenstein')),
    (128, _('Sri Lanka')),
    (129, _('Liberia')),
    (130, _('Lesotho')),
    (131, _('Lithuania')),
    (132, _('Luxembourg')),
    (133, _('Latvia')),
    (134, _('Libya')),
    (135, _('Morocco')),
    (136, _('Monaco')),
    (137, _('Moldova')),
    (138, _('Montenegro')),
    (139, _('Madagascar')),
    (140, _('Marshall Islands')),
    (141, _('Macedonia [FYROM]')),
    (142, _('Mali')),
    (143, _('Myanmar [Burma]')),
    (144, _('Mongolia')),
    (145, _('Macau')),
    (146, _('Northern Mariana Islands')),
    (147, _('Martinique')),
    (148, _('Mauritania')),
    (149, _('Montserrat')),
    (150, _('Malta')),
    (151, _('Mauritius')),
    (152, _('Maldives')),
    (153, _('Malawi')),
    (154, _('Mexico')),
    (155, _('Malaysia')),
    (156, _('Mozambique')),
    (157, _('Namibia')),
    (158, _('New Caledonia')),
    (159, _('Niger')),
    (160, _('Norfolk Island')),
    (161, _('Nigeria')),
    (162, _('Nicaragua')),
    (163, _('Netherlands')),
    (164, _('Norway')),
    (165, _('Nepal')),
    (166, _('Nauru')),
    (167, _('Niue')),
    (168, _('New Zealand')),
    (169, _('Oman')),
    (170, _('Panama')),
    (171, _('Peru')),
    (172, _('French Polynesia')),
    (173, _('Papua New Guinea')),
    (174, _('Philippines')),
    (175, _('Pakistan')),
    (176, _('Poland')),
    (177, _('Saint Pierre and Miquelon')),
    (178, _('Pitcairn Islands')),
    (179, _('Puerto Rico')),
    (180, _('Palestinian Territories')),
    (181, _('Portugal')),
    (182, _('Palau')),
    (183, _('Paraguay')),
    (184, _('Qatar')),
    (185, _('Réunion')),
    (186, _('Romania')),
    (187, _('Serbia')),
    (188, _('Russia')),
    (189, _('Rwanda')),
    (190, _('Saudi Arabia')),
    (191, _('Solomon Islands')),
    (192, _('Seychelles')),
    (193, _('Sudan')),
    (194, _('Sweden')),
    (195, _('Singapore')),
    (196, _('Saint Helena')),
    (197, _('Slovenia')),
    (198, _('Svalbard and Jan Mayen')),
    (199, _('Slovakia')),
    (200, _('Sierra Leone')),
    (201, _('San Marino')),
    (202, _('Senegal')),
    (203, _('Somalia')),
    (204, _('Suriname')),
    (205, _('São Tomé and Príncipe')),
    (206, _('El Salvador')),
    (207, _('Syria')),
    (208, _('Swaziland')),
    (209, _('Turks and Caicos Islands')),
    (210, _('Chad')),
    (211, _('French Southern Territories')),
    (212, _('Togo')),
    (213, _('Thailand')),
    (214, _('Tajikistan')),
    (215, _('Tokelau')),
    (216, _('Timor-Leste')),
    (217, _('Turkmenistan')),
    (218, _('Tunisia')),
    (219, _('Tonga')),
    (220, _('Turkey')),
    (221, _('Trinidad and Tobago')),
    (222, _('Tuvalu')),
    (223, _('Taiwan')),
    (224, _('Tanzania')),
    (225, _('Ukraine')),
    (226, _('Uganda')),
    (227, _('U.S. Minor Outlying Islands')),
    (228, _('United States of America')),
    (229, _('Uruguay')),
    (230, _('Uzbekistan')),
    (231, _('Vatican City')),
    (232, _('Saint Vincent and the Grenadines')),
    (233, _('Venezuela')),
    (234, _('British Virgin Islands')),
    (235, _('U.S. Virgin Islands')),
    (236, _('Vietnam')),
    (237, _('Vanuatu')),
    (238, _('Wallis and Futuna')),
    (239, _('Samoa')),
    (240, _('Kosovo')),
    (241, _('Yemen')),
    (242, _('Mayotte')),
    (243, _('South Africa')),
    (244, _('Zambia')),
    (245, _('Zimbabwe')),
)